# Default values
rbac:
  create: true

admissionRegistration:
  # Possible values: Ignore and Fail
  failurePolicy: Ignore
  namespaceSelector:
    matchLabels:
      affinity-injection: enabled

controller:

  ## controller container image
  ##
  image:
    repository: tolleiv/k8s-affinity-admission
    tag: latest
    pullPolicy: Always

  ## controller replica count
  ##
  replicaCount: 1

  ## Affinity configuration for the controller pod
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  ##
  affinity: {}

  ## Node tolerations for scheduling to nodes with taints
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  ##
  tolerations: []

  ## Node labels for controller pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}

  ## Annotations to be added to controller pods
  ##
  podAnnotations: {}

  args:
    ## Operation mode for the controller
    ## Possible values: denyMissing, patchMissing, patchAlways
    ##
    mode: patchMissing

    ## Affinity patch the controller should apply
    ##
    affinityPatch: {}

    ## Logging verbosity level
    verbosity: 4

  serviceAccount: k8s-affinity-admission-controller
  tls:
    # Admission controller server will inherit this CA from the
    # extension-apiserver-authentication ConfigMap if available.
    requestHeaderCA:
  service:
    type: NodePort
    port: 443
    targetPort: 8443